import { ConnectorIds } from './wagmi.config'

const HOST = typeof window !== 'undefined' ? window.location.href : ''

export const wallets: Wallet[] = [
  {
    injected: true,
    name: 'Injected',
    connectorId: ConnectorIds.Injected,
    etherId: null,
    mobileOnly: false,
    iconURI: '/wallets/injected.png',
    downloadUrl: null,
    deepLink: null,
  },
  {
    injected: false,
    name: 'MetaMask',
    connectorId: ConnectorIds.Injected,
    etherId: 'isMetaMask',
    mobileOnly: false,
    iconURI: '/wallets/metamask.png',
    downloadUrl: 'https://metamask.io/download/',
    deepLink: `https://metamask.app.link/dapp/${HOST}`,
  },
  {
    injected: false,
    name: 'Opera Wallet',
    connectorId: ConnectorIds.Injected,
    etherId: 'isOpera',
    mobileOnly: false,
    iconURI: '/wallets/opera.png',
    downloadUrl: 'https://www.opera.com/crypto/next',
    deepLink: null,
  },
  {
    injected: false,
    name: 'MathWallet',
    connectorId: ConnectorIds.Injected,
    etherId: 'isMathWallet',
    mobileOnly: false,
    iconURI: '/wallets/mathwallet.png',
    downloadUrl: 'https://mathwallet.org/',
    deepLink: `mathwallet://mathwallet.org?action=link&value=${HOST}`,
  },
  {
    injected: false,
    name: 'SafePal',
    connectorId: ConnectorIds.Injected,
    etherId: 'isSafePal',
    mobileOnly: false,
    iconURI: '/wallets/safepal.png',
    downloadUrl: 'https://safepal.io/download',
    deepLink: null,
  },
  {
    injected: false,
    name: 'TokenPocket',
    connectorId: ConnectorIds.Injected,
    etherId: 'isTokenPocket',
    mobileOnly: false,
    iconURI: '/wallets/tokenpocket.png',
    downloadUrl: 'https://www.tokenpocket.pro/',
    deepLink: `https://tokenpocket.github.io/applink?dappUrl=${HOST}`,
  },
  {
    injected: false,
    name: 'Coin98',
    connectorId: ConnectorIds.Injected,
    etherId: 'isCoin98',
    mobileOnly: false,
    iconURI: '/wallets/coin98.png',
    downloadUrl: 'https://coin98.net/',
    deepLink: null,
  },
  {
    injected: false,
    name: 'Trust Wallet',
    connectorId: ConnectorIds.Injected,
    etherId: 'isTrust',
    mobileOnly: true,
    iconURI: '/wallets/trustwallet.png',
    downloadUrl: 'https://trustwallet.com/',
    deepLink: `https://link.trustwallet.com/open_url?coin_id=714&url=${HOST}`,
  },
  // {
  //   injected: false,
  //   name: "Rice Wallet",
  //   connectorId: ConnectorIds.Injected,
  //   etherId: "isRiceWallet",
  //   mobileOnly: true,
  //   iconURI: "/wallets/ricewallet.png",
  //   downloadUrl: "https://ricewallet.io/",
  //   deepLink: null,
  // },
  {
    injected: false,
    name: 'Wallet Connect',
    connectorId: ConnectorIds.WalletConnect,
    etherId: null,
    mobileOnly: false,
    iconURI: '/wallets/walletconnect.png',
    downloadUrl: null,
    deepLink: null,
  },
]
